[snowflake]
user = "user"
password = "password"
account = "account"
warehouse = "warehouse"
database = "database"
schema = "schema"
role = "role"

[mysql]
user = "mysql"
password = "mysql"
host = "store_a"
port = 3306
database = "retail_supply_chain"