my_snowflake_db:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: <your-account>

      user: <your-username>
      password: <your-password>

      role: <your-role>
      database: <your-database>
      warehouse: <your-warehouse>
      schema: <your-schema>
      threads: 4
      client_session_keep_alive: False