CREATE DATABASE IF NOT EXISTS RETAIL_SUPPLY_CHAIN;

CREATE SCHEMA IF NOT EXISTS LANDING;
CREATE SCHEMA IF NOT EXISTS DIMENSION;
CREATE SCHEMA IF NOT EXISTS FACT;
CREATE SCHEMA IF NOT EXISTS SNAPSHOT;

USE DATABASE RETAIL_SUPPLY_CHAIN;
USE SCHEMA LANDING;

CREATE TABLE IF NOT EXISTS LANDING.Products (
    ProductID INT AUTOINCREMENT PRIMARY KEY,
    Name VARCHAR(100),
    Category VARCHAR(50),
    Price DECIMAL(10, 2)
);

CREATE TABLE IF NOT EXISTS LANDING.Suppliers (
    SupplierID INT AUTOINCREMENT PRIMARY KEY,
    Name VARCHAR(100),
    ContactName VARCHAR(100),
    ContactEmail VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS LANDING.Warehouses (
    WarehouseID INT AUTOINCREMENT PRIMARY KEY,
    Location VARCHAR(100),
    Capacity INT
);

CREATE TABLE IF NOT EXISTS LANDING.Stock (
    WarehouseID INT,
    ProductID INT,
    Quantity INT,
    PRIMARY KEY (WarehouseID, ProductID),
    FOREIGN KEY (WarehouseID) REFERENCES LANDING.Warehouses(WarehouseID),
    FOREIGN KEY (ProductID) REFERENCES LANDING.Products(ProductID)
);

CREATE TABLE IF NOT EXISTS LANDING.Orders (
    OrderID INT AUTOINCREMENT PRIMARY KEY,
    OrderDate DATE,
    CustomerName VARCHAR(100),
    CustomerAddress VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS LANDING.OrderItems (
    OrderItemID INT AUTOINCREMENT PRIMARY KEY,
    OrderID INT,
    ProductID INT,
    Quantity INT,
    Price DECIMAL(10, 2),
    FOREIGN KEY (OrderID) REFERENCES LANDING.Orders(OrderID),
    FOREIGN KEY (ProductID) REFERENCES LANDING.Products(ProductID)
);

CREATE TABLE IF NOT EXISTS LANDING.Shipments (
    ShipmentID INT AUTOINCREMENT PRIMARY KEY,
    SupplierID INT,
    WarehouseID INT,
    ShipmentDate DATE,
    FOREIGN KEY (SupplierID) REFERENCES LANDING.Suppliers(SupplierID),
    FOREIGN KEY (WarehouseID) REFERENCES LANDING.Warehouses(WarehouseID)
);

CREATE TABLE IF NOT EXISTS LANDING.ShipmentItems (
    ShipmentItemID INT AUTOINCREMENT PRIMARY KEY,
    ShipmentID INT,
    ProductID INT,
    Quantity INT,
    FOREIGN KEY (ShipmentID) REFERENCES LANDING.Shipments(ShipmentID),
    FOREIGN KEY (ProductID) REFERENCES LANDING.Products(ProductID)
);

CREATE TABLE IF NOT EXISTS LANDING.Sales (
    SaleID INT AUTOINCREMENT PRIMARY KEY,
    SaleDate DATE,
    ProductID INT,
    Quantity INT,
    TotalAmount DECIMAL(10, 2),
    FOREIGN KEY (ProductID) REFERENCES LANDING.Products(ProductID)
);